'use client'
import BreadCrumb from "@/componenets/BreadCrumb";
import NavBar from "@/componenets/NavBar";
import SideBar from "@/componenets/SideBar";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const pathname = usePathname();
    return (


        <div className={`flex`}>
            <SideBar />
            <div className={`flex flex-col w-full h-screen overflow-scroll z-0`}>
                <NavBar />
                <div className={` flex flex-col dashboard-section py-[1.5rem] px-[2rem] gap-[40px] font-sans`} onClick={() => {
                    const logout_container = document.querySelector('.logout-container');
                    if (logout_container && !logout_container.classList.contains('hidden')) {
                        console.log("hello");
                        logout_container.classList.toggle('hidden');

                    }

                }
                }>
                    <BreadCrumb pathname={pathname} />
                    {children}
                </div>
            </div>

        </div>


    );
}
