'use client'
import BreadCrumb from "@/componenets/BreadCrumb";
import NavBar from "@/componenets/NavBar";
import SideBar from "@/componenets/SideBar";
import { CustomerProvider } from "@/contexts/CustomerContext";
import { UserProvider } from "@/contexts/UserContext";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function CustomersLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const pathname = usePathname();
    return (
        <CustomerProvider>

            {children}

        </CustomerProvider>

    );
}
